---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: stilton
  labels:
    app: cheese
    cheese: stilton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: stilton
  template:
    metadata:
      labels:
        app: cheese
        task: stilton
        version: v0.0.1
    spec:
      containers:
        - name: cheese
          image: errm/cheese:stilton
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
            limits:
              memory: 50Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stilton
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: cheese
    task: stilton
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cheese
  annotations: []
    # kubernetes.io/ingress.class: traefik
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # kubernetes.io/tls-acme: "true"
spec:
  tls: []
#    - hosts:
#        - "stilton.test"
#      secretName: stilton-web-tls
  rules:
  - host: stilton.test
    http:
      paths:
      - path: /
        backend:
          serviceName: stilton
          servicePort: http
